
SELECT 
P.NOME AS "PRODUTO",
P.PRECO,
C.NOME AS "CATEGORIA"
FROM PRODUTO P
JOIN CATEGORIA C  
JOIN PRODUTO_CATEGORIA PC  ON P.ID =  PC.PRODUTO_ID 
AND C.ID = PC.CATEGORIA_ID
-- ------------------------------
SELECT 
C.NOME AS "CIDADE",
E.NOME AS "ESTADO"
FROM CIDADE C
JOIN ESTADO E ON C.ESTADO_ID = E.ID
-- -------------------------------
SELECT
C.NOME,
C.EMAIL,
C.CPF_OU_CNPJ,
T.TELEFONES AS "TEL",
E.LOGRADOURO,
E.NUMERO,
E.BAIRRO,
E.COMPLEMENTO,
CI.NOME AS "CIDADE",
E.CEP,
ES.NOME AS "ESTADO"
FROM CLIENTE  C
JOIN TELEFONE T ON C.ID = T.CLIENTE_ID
JOIN ENDERECO E ON C.ID = E.CLIENTE_ID
JOIN CIDADE CI ON E.CIDADE_ID = CI.ID
JOIN ESTADO ES ON CI.ESTADO_ID = ES.ID 
-- ----------------------------------
SELECT 
PRO.NOME AS "PRODUTO",
IP.PRECO,
IP.QUANTIDADE,
PE.INSTANTE,
E.BAIRRO,
E.LOGRADOURO,
E.NUMERO,
C.NOME
FROM ITEM_PEDIDO IP
JOIN PEDIDO PE ON PE.ID = IP.PEDIDO_ID
JOIN CLIENTE C ON C.ID = PE.CLIENTE_ID
JOIN ENDERECO E ON  E.ID = PE.ENDERECO_DE_ENTREGA_ID
JOIN PRODUTO PRO ON PRO.ID = IP.PRODUTO_ID